asset: mungye-macos-amd64.tar.gz
tap: mandx/homebrew-mungye/Formula/mungye.rb
template: >
  class Mungye < Formula
    desc     "$REPO_DESCRIPTION"
    homepage "$REPO_WEBITE"
    version  "$STABLE_VERSION"
    url      "$STABLE_ASSET_URL"
    sha256   "$STABLE_ASSET_SHA256"

    def install
      bin.install "mungye"
    end
  end
